const Path = require('path');
const Protobuf = require('protobufjs');

let root = Protobuf.loadSync(Path.join(__dirname, '../../assets/protocol.proto'));

module.exports = {
    Packet: root.lookupType('Packet'),
    LoginRequest: root.lookupType('LoginRequest'),
    LoginResponse: root.lookupType('LoginResponse'),
    HeartBeatRequest: root.lookupType('HeartBeatRequest'),
    HeartBeatResponse: root.lookupType('HeartBeatResponse'),
    SetRoundBeginFlow: root.lookupType('SetRoundBeginFlow'),
    SetRoundFlow: root.lookupType('SetRoundFlow'),
    AddFlag: root.lookupType('AddFlag'),
    NickName: root.lookupType('NickName'),
    UnlockingItemRequest: root.lookupType('UnlockingItemRequest'),
    UnlockingItemResponse: root.lookupType('UnlockingItemResponse'),
    SetShortInfoRequest: root.lookupType('SetShortInfoRequest'),
    CostDiamond: root.lookupType('CostDiamond'),
    CostDiamondResponse: root.lookupType('CostDiamondResponse'),
    BlessRequest: root.lookupType('BlessRequest'),
    BlessResponse: root.lookupType('BlessResponse'),
    OpenPackageSlotRequest: root.lookupType('OpenPackageSlotRequest'),
    OpenPackageSlotResponse: root.lookupType('OpenPackageSlotResponse'),
    GetPackagePointRequest: root.lookupType('GetPackagePointRequest'),
    GetPackagePointResponse: root.lookupType('GetPackagePointResponse'),
    GetItemRequest: root.lookupType('GetItemRequest'),
    GetItemResponse: root.lookupType('GetItemResponse'),
    GetElementEnergy: root.lookupType('GetElementEnergy'),
    GetPackageRequest: root.lookupType('GetPackageRequest'),
    GetPackageResponse: root.lookupType('GetPackageResponse'),
    GetSkillRecipeRequest: root.lookupType('GetSkillRecipeRequest'),
    GetSkillRecipeResponse: root.lookupType('GetSkillRecipeResponse'),
    GetStoryLevelRewardRequest: root.lookupType('GetStoryLevelRewardRequest'),
    GetStoryLevelRewardResponse: root.lookupType('GetStoryLevelRewardResponse'),
    ElementEnergyNotify: root.lookupType('ElementEnergyNotify'),
    SetStoryLevel: root.lookupType('SetStoryLevel'),
    EquipItemRequest: root.lookupType('EquipItemRequest'),
    EquipItemResponse: root.lookupType('EquipItemResponse'),
    OpenPackageRequest: root.lookupType('OpenPackageRequest'),
    OpenPackageResponse: root.lookupType('OpenPackageResponse'),
    GetDailySignReward: root.lookupType('GetDailySignReward'),
    GetDailySignRewardResponse: root.lookupType('GetDailySignRewardResponse'),
    DiamondNotify: root.lookupType('DiamondNotify'),
    HonorRewardNotify: root.lookupType('HonorRewardNotify'),
    IDIPBanNotify: root.lookupType('IDIPBanNotify'),
    IDIPRemindNotify: root.lookupType('IDIPRemindNotify'),
    UnlockedItemRequest: root.lookupType('UnlockedItemRequest'),
    UnlockedItemResponse: root.lookupType('UnlockedItemResponse'),
    UnlockRoleRequest: root.lookupType('UnlockRoleRequest'),
    UnlockRoleResponse: root.lookupType('UnlockRoleResponse'),
    ChangeRoleRequest: root.lookupType('ChangeRoleRequest'),
    ChangeRoleResponse: root.lookupType('ChangeRoleResponse'),
    FreeDiamondRequest: root.lookupType('FreeDiamondRequest'),
    FreeDiamondResponse: root.lookupType('FreeDiamondResponse'),
    ReviveRequest: root.lookupType('ReviveRequest'),
    ReviveResponse: root.lookupType('ReviveResponse'),
    GameInfo: root.lookupType('GameInfo'),
    MealTicketResponse: root.lookupType('MealTicketResponse')
}